# Generated by Django 6.0.5 on 2026-08-13 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('authentication', '0004_patientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='authentication.specialistprofile'),
        ),
        migrations.DeleteModel(
            name='Specialist',
        ),
    ]
