# Generated by Django 6.0.5 on 2026-08-12 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursecertificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecertificate',
            name='recommendation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='coursecertificate',
            name='recommendation_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecertificate',
            name='specialist_recommendation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='coursecertificate',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL),
        ),
    ]
